version: '3.4'
services:
  community_cms:
    ports:
      - 8055:8055
    restart: unless-stopped

  community_cache:
    restart: unless-stopped

  community_web:
    build:
      network: prodeko-docker-net
    restart: unless-stopped

  community_search:
    restart: unless-stopped

networks:
  default:
    external:
      name: prodeko-docker-net
