version: '3.4'
services:
  database:
    network_mode: host
    env_file:
      - .env.dev

  directus:
    network_mode: host
    env_file:
      - .env.dev

  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    network_mode: host
    env_file:
      - .env.dev

  wait:
    network_mode: host
